# Generated by Django 2.0.7 on 2018-07-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, choices=[('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Living Room', 'Living Room'), ('Hallway', 'Hallway')], max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('pin_number', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
