# Generated by Django 2.0.7 on 2018-07-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180713_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetypes',
            options={'verbose_name_plural': 'DeviceTypes'},
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicetypes',
            name='iconclass',
            field=models.CharField(blank=True, choices=[('nb-alert', 'nb-alert'), ('nb-angle-double-left', 'nb-angle-double-left'), ('nb-audio', 'nb-audio'), ('nb-close', 'nb-close'), ('nb-coffee-maker', 'nb-coffee-maker'), ('nb-compose', 'nb-compose'), ('nb-edit', 'nb-edit'), ('nb-flame-circled', 'nb-flame-circled'), ('nb-gear', 'nb-gear'), ('nb-grid-a', 'nb-grid-a'), ('nb-heart', 'nb-heart'), ('nb-keypad', 'nb-keypad'), ('nb-lightbulb', 'nb-lightbulb'), ('nb-locked', 'nb-locked'), ('nb-pause', 'nb-pause'), ('nb-play', 'nb-play'), ('nb-phone', 'nb-phone'), ('nb-power', 'nb-power'), ('nb-power-circled', 'nb-power-circled'), ('nb-rainy', 'nb-rainy'), ('nb-roller-shades', 'nb-roller-shades'), ('nb-shuffle', 'nb-shuffle'), ('nb-star', 'nb-star'), ('nb-sunny', 'nb-sunny'), ('nb-trash', 'nb-trash'), ('nb-volume-high', 'nb-volume-high'), ('nb-volume-mute', 'nb-volume-mute')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicetypes',
            name='style_type',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning')], max_length=255, null=True),
        ),
    ]
