# Generated by Django 2.0.7 on 2018-07-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry', '0001_initial'),
        ('rooms', '0003_auto_20180714_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='pin_number',
        ),
        migrations.AddField(
            model_name='device',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='raspberry.GPIO_pins'),
        ),
    ]
