# Generated by Django 2.0.7 on 2018-07-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20180716_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='state',
        ),
    ]
