# Generated by Django 2.0.7 on 2018-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpio_pins',
            options={'verbose_name_plural': 'GPIO pins'},
        ),
        migrations.AlterField(
            model_name='gpio_pins',
            name='pin',
            field=models.PositiveIntegerField(choices=[(5, 5), (6, 6), (13, 13), (19, 19), (26, 26), (21, 21), (20, 20), (16, 16)]),
        ),
    ]
