# Generated by Django 2.0.7 on 2018-07-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry', '0002_auto_20180719_0633'),
        ('raspberry', '0002_auto_20180718_0901'),
    ]

    operations = [
    ]
